### ISSUE TITLE
Release year not in folder name 

### ISSUE THREAD

**Issue by marc0janssen** [vche/pycliarr#14]
Hi Vivien,

The release year is not added to the folder name when a movie is grabbed and saved.

eg. The Virtuoso (2021)

```
 root_path = self.get_root_folder()       
 movie_info.path = root_path["path"] + movie_info.title
```

**Comment by vche** [comment]
Hi,
That is not an bug, the format of the movie folder is up to the user.
That said, it makes sense to use the same default format than radarr, so I will update this. 
But more importantly, I will add an optional parameter to add_movie() and add_serie() to allow specifying the movie/serie folder.

**Comment by marc0janssen** [comment]
I meant to say it is a bug. Just something I missed and liked to be added. 

Nice suggestions.
