### ISSUE TITLE
Feature request : Can the root folder be selected.

### ISSUE THREAD

**Issue by marc0janssen** [vche/pycliarr#15]
When adding a movie or series, pycliarr always get the first root older. 

Some users have multiple root folders like: 
 /series
 /series2

I would like to be able to select those. 

Thanks in advance.

**Comment by vche** [comment]
I will update get_root_folder() to return all root folders, not only the first result.

But pycliarr is a merely client. While it provide default values for the folder, those are only default for basic usage.

The logic of managing and selecting root folders is better  be implemented by the users. Same than radarr/sonarr merely provide you the path, but you build the folder path.

With several root folders, you will get them all using get_root_folders() and must build the movie/serie path you want to use. You can then pass it to add_movie/add_folder.

I will provide a helper build_serie_path() to build the default name by selecting the folder though, but I do not want to put that option as parameter in add_serie/movie as it is too specific.

I'll provide you with usage example after implementation

**Comment by vche** [comment]
Here's an example how you can customise the root path used for an movie. By implementing your own "build_movie_path()" you can customise even further (use get_root_folder() to get all root paths/ids):
```
movie = radarr_cli.radarr_cli.("some movie")
movie_path = radarr_cli.build_movie_path(movie, root_folder_id = 2)
radarr_cli.add_movie(quality=1, movie_info=movie, path=movie_path)
```

Similarly you have ```build_serie_path()``` for series with the same arguments.

**Comment by marc0janssen** [comment]
movie = radarr_cli.radarr_cli.("some movie")

I don't get the radarr_cli.radarr_cli part

Is the movie object a string title?

**Comment by vche** [comment]
Copy paste error, it's the lookup:
radarr_cli.lookup_movie("some movie")

**Comment by marc0janssen** [comment]
Thanks again !!! All worked out fine!!

**Comment by vche** [comment]
no problem ! I’m glad that everything works as intended !
