### ISSUE TITLE
Question: Tagging a movie when added

### ISSUE THREAD

**Issue by marc0janssen** [vche/pycliarr#17]
Hi There, 

I have an question. I like to add a tag when a movie is added -->add_movie().

Do I do that via 
movie_info: Optional[RadarrMovieItem] = None, ???

I hope you can advise.

**Comment by vche** [comment]
Hi,
movie_info parameter is used to specify the description of the movie to add if you don’t specify an imdv/tmdb id.

If you do specify one of those ids, the movie_info parameter is not taken into account, but instead the movie description is fetched from imdv/tmdb
If you don’t, and you build the movie info yourself by calling manually lookup_movie, then yes you can add the tags in there.


To sum up:

Something like this would work:
```
mymovie = radarr.lookup_movie(imdb_id=movie_id)
…
mymovie.tags = [’tag1’, ’tag2’]
radarr.add_movie(movie_info=mymovie,...)
```

Something like this will not work:
```
mymovie = RadarrMovieItem()
mymovie.tags = [’tag1’, ’tag2’]
radarr.add_movie(imdb_id=movie_id, movie_info=mymovie,...)
```

**Comment by marc0janssen** [comment]
Works perfectly….thanks!!!!
