### ISSUE TITLE
addImportExclusion

### ISSUE THREAD

**Issue by marc0janssen** [vche/pycliarr#18]
Hi there,

I like to add my deleted movies to the exclusion list, but this does not work using this API.

In the docs they talk about addImportExclusion but you seem to use addExclusion

Can you please verify?  Thanks

**Comment by vche** [comment]
Your're right, the parameter has been renamed in api v3. Sending a new release.

**Comment by marc0janssen** [comment]
Great Vivien! Looking forward!

**Comment by vche** [comment]
released v1.0.15, re open this ticket if it doesn't solve this.

**Comment by marc0janssen** [comment]
Hi Vivien.... 

It is not working for the Sonarr API.... I checked the webz and there need to be a addImportExclusion: bool too for SONARR!

Can you please verify???
