### ISSUE TITLE
add_exclusion Sonarr 

### ISSUE THREAD

**Issue by marc0janssen** [vche/pycliarr#21]
Successfully installed m2r2-0.3.1 pycliarr-1.0.16

This still doesn't work... Is add_exclusion simply not supported by Sonarr??

**Comment by vche** [comment]
as i pointed out, it is in the api but i found others in the api not actuallu implemented.
also, please reopen tickets rather than creating new ones when it is about the same

**Comment by marc0janssen** [comment]
Right. Vivien. I then misunderstood you
