### ISSUE TITLE
Media path missing a "/" between "rootpath" and the movie title

### ISSUE THREAD

**Issue by marc0janssen** [vche/pycliarr#23]
Seems the new version of pycliarr does not parse the "save/download" path correctly.

Said the "rootpath" in Radarr is "/movies" and the movie title is focus (2015).
The path is build like:  /moviefocus(2015) instead of /movie/focus(2015).  The "/" is missing in the path.

Seems like "build_item_path" method is not concatenating the strings correctly.  

       return str(root_path["path"]) + self.to_path(title) ==>  return str(root_path["path"]) + "/" + self.to_path(title) 

(alternative ==> return f"{root_path['path']}/{self.to_path(title)}" )

 def build_item_path(self, title: str, root_folder_id: int = 0) -> str:
        """Build an item folder path using the root folder specified.
        Args:
            title (str): Title to add to root path. All invalid characters are removed
            root_folder_id (int): Id of the root folder (can be retrieved with get_root_folder())
                If the id is not found or not specified, the first root folder in the list is used.
        Returns: Full path of the serie in the format <root path>/<serie name>
        """
        root_paths = self.get_root_folder()
        root_path = root_paths[0]
        for path in root_paths:
            if path["id"] == root_folder_id:
                root_path = path
        return str(root_path["path"]) + self.to_path(title)

**Comment by marc0janssen** [comment]
self.get_root_folder() In the method: ==> build_movie_path

returns paths without a ending "/"

**Comment by vche** [comment]
The api v3 doesn't include the trailng / anymore. Fixed in the latest release.

```
(pyvenv) viv@lapdwarf ~/d/pycliarr (master  ⚡ 2)# API=v3/rootfolder curl -X GET "http://192.168.0.199:8989/api/$API?apikey=xxxxx" -H "accept: application/json"
[
  {
    "path": "/tv",
...
]
(pyvenv) viv@lapdwarf ~/d/pycliarr (master  ⚡ 2)# API=rootfolder curl -X GET "http://192.168.0.199:8989/api/$API?apikey=xxxx" -H "accept: application/json"
[
  {
    "path": "/tv/",
...
]
```

Fixed this to handle both cases. Please close if this solves your issue

**Comment by marc0janssen** [comment]
I tested it and it works!  

Merci again!
