### ISSUE TITLE
Tip for you: build_movie_path and build_serie_path

### ISSUE THREAD

**Issue by marc0janssen** [vche/pycliarr#26]
Hi Vivien, 

Your methods build_movie_path and build_serie_path are NOT passing root_folder_id to the method "build_item_path".

It's just a tip. I just adapted both methods to my own code so I could build the path... then I noticed it.

Use it to your advantage.

Marco

**Comment by vche** [comment]
oh ! thanks ! definitely a bug and a miss in my unit tests ! I'll fix this

**Comment by marc0janssen** [comment]
I edit my code in visual studio code from microsoft... it warns/highlights variables/properties that are unused. 
That's how I noticed .
