### ISSUE TITLE
add params to get_queue

### ISSUE THREAD

**Issue by hendrix04** [vche/pycliarr#29]
get_queue accepts query parameters:

- Sonarr
  - page
    - int
  - pageSize
    - int
  - sortDirection
    - enum
      - ascending
      - descending
  - sortKey
    - enum
      - series.sortTitle
      - episode
      - episode.title
      - quality
      - estimatedCompletionTime
      - progress
  - includeUnknownSeriesItems
    - boolean
 - Radarr
   - page
     - int
   - pageSize
     - int
   - sortDirection
     - enum
       - ascending
       - descending
   - sortKey
     - enum
       - movies.sortTitle
       - episode
       - languages
       - quality
       - estimatedCompletionTime
       - timeleft
       - progress
   - includeUnknownMovieItems
     - boolean

**Comment by vche** [comment]
Fixed in v1.0.19
