### ISSUE TITLE
Radarr Search Missing only for available/released items

### ISSUE THREAD

**Issue by JoshDi** [vche/pycliarr#31]
Im pretty sure this is an enhancement, but maybe it is possible within the current pycliarr package. 

Is there a way to use the radarr search-missing functionality but only search for items that are available?

**Comment by vche** [comment]
search-missing  is calling directly a function (wanted/missing) from radarr, so it basically does the same than what you can do in the UI when searching for movies.

this api does not take any parameter and just trigger an operation in radarr. So pycliarr can't change its behavior unfortunately.
