### ISSUE TITLE
Sonarr and folderSeason

### ISSUE THREAD

**Issue by Pherscho** [vche/pycliarr#32]
Hello,

This is an enhancement request.  When using pycliarr with Sonarr the default option for "seasonFolder" is false.  It would be nice to have a way to change that default to true.

Maybe a generic way to change any option would be even better,  But this can be more complex because some settings are a json set.   Maybe something like:

--set-param "seasonFolder=true"
--set-param "qualityProfileId=5"
--set-param "seasons[0].monitored=true"

Thanks again for all your work.

**Comment by vche** [comment]
Hi, thanks for the idea, I like it.

I agree it would be great to allow default options customisation. Let me think about the implementation and possible user interface and I'll work on this asap.

**Comment by vche** [comment]
Implemented, have a look at the Config CLI documentation in the README (or main project page)

**Comment by Pherscho** [comment]
Hi, everything is working as expected.  Thanks, really appreciated.  Just a question, now I am getting this output all the time, it is supposed to be there?  any way to hide it? is tarace meant to be trace?


tarace {'CliAddMovieCommand.--quality': None, 'CliAddMovieCommand.--root-folder': '/Video3/Movies', 'CliAddSerieCommand.--quality': None, 'CliAddSerieCommand.--root-folder': '/Video2/TV', 'CliAddSerieCommand.--season-folders': True, 'CliAddSerieCommand.--seasons': None, 'CliDeleteMovieCommand.--delfiles': False, 'CliDeleteMovieCommand.--exclude': False, 'CliDeleteSerieCommand.--delfiles': False, 'CliDeleteSerieCommand.--exclude': False, 'CliGetBlocklistCommand.--page': 1, 'CliGetBlocklistCommand.--page-size': 20, 'CliGetBlocklistCommand.--sort-dir': 'descending', 'CliGetBlocklistCommand.--sort-key': 'date', 'CliGetCalendarCommand.--end': None, 'CliGetCalendarCommand.--start': None, 'CliGetQueueCommand.--exclude-unknown': False, 'CliGetQueueCommand.--page': 1, 'CliGetQueueCommand.--page-size': 20, 'CliGetQueueCommand.--sort-dir': 'ascending', 'CliGetQueueCommand.--sort-key': 'progress', 'CliWantedCommand.--page': 1, 'CliWantedCommand.--page-size': 10, 'CliWantedCommand.--sort-dir': 'asc', 'CliWantedCommand.--sort-key': 'airDateUtc'}
PyCliarr version 1.0.23

**Comment by vche** [comment]
oh no, a debug trace not removed. i'll upload  a new revision right now

**Comment by vche** [comment]
updated
