### ISSUE TITLE
Sonarr rename command now requires series_id

### ISSUE THREAD

**Issue by hollanbm** [vche/pycliarr#34]
```python
self.sonarr_cli._sendCommand(
    {
        "name": "RenameFiles",
        "files": [1,2,3],
        "seriesId": 1,
    }
)
```

**Comment by hollanbm** [comment]
I did my best to create a PR, but I wasn't able to get the dev env stood on my apple silicon mac. 

I also created the skeleton for a devContainer if you're interested

**Comment by vche** [comment]
Thanks for your contribution. I've left a couple comments and suggested changes to fix them. Once fixed the tests should pass and I can merge this and generate a new release.

For the dev environment, it's easy, if you follow [this](https://github.com/vche/pycliarr?tab=readme-ov-file#using-pixi).
Basically install [pixi](https://pixi.sh/latest/) then run `pixi run test` in a terminal.

**Comment by hollanbm** [comment]
> Thanks for your contribution. I've left a couple comments and suggested changes to fix them. Once fixed the tests should pass and I can merge this and generate a new release.
> 
> 
> 
> For the dev environment, it's easy, if you follow [this](https://github.com/vche/pycliarr?tab=readme-ov-file#using-pixi).
> 
> Basically install [pixi](https://pixi.sh/latest/) then run `pixi run test` in a terminal.

Thanks for the feedback, I'll try and see what I can get done later tonight.

I got pixi installed, but I wasn't able to complete `pixi build` with my Apple Silicon Mac. I even modified the pixi.toml to add `osx-arm64` -- I'll give it a second try though

**Comment by vche** [comment]
i'm working on silicon mac as well so it should be working fine. pixi.toml already contains `platforms = ["osx-64"]` which is what's needed.

i can see the readme is very wrong, the command is `pixi run build`
then to run the tests `pixi run test`

if it doesn't work and want to give me the error i can help. I'm updating the README to fix those in the meantime

**Comment by hollanbm** [comment]
> i'm working on silicon mac as well so it should be working fine. pixi.toml already contains `platforms = ["osx-64"]` which is what's needed.
> 
> i can see the readme is very wrong, the command is `pixi run build` then to run the tests `pixi run test`
> 
> if it doesn't work and want to give me the error i can help. I'm updating the README to fix those in the meantime

I was able to get the dev environment stood up, and the test suite ran locally. I wasn't able to get it to compile natively on ARM, but when emulated with rosetta it does work.

I do find that strange though, as I'm using your library in a [project](https://github.com/hollanbm/sonarr-series-scanner) of mine, which I am currently building/deploying to ARM systems.

**Comment by vche** [comment]
I've merged and published the new release. Thanks for the contribution !

Not too sure what you mean with compilation and arm. python doesn't really compile and especially not cross compile. it uses on whatever python engine is installed. Here I am merely testing on 2 different python versions for backward compatibiilty.

**Comment by bholland-bh** [comment]
> I've merged and published the new release. Thanks for the contribution !
> 
> 
> 
> Not too sure what you mean with compilation and arm. python doesn't really compile and especially not cross compile. it uses on whatever python engine is installed. Here I am merely testing on 2 different python versions for backward compatibiilty.

I'm fairly new to python, so forgive me, still learning the ins and outs.

When I created a new `python-3.12` venv, and ran `pixi run build`, I got a warning about using Rosetta for emulation. But it installed, and ran w/o issue, unit tests and all.

When I updated `pixi.toml` to add `osx-arm64`, `pixi run build` failed to complete successfully.

Probably not worth investigating, when Rosetta emulation works just fine.

Thanks for all your help!

**Comment by hollanbm** [comment]
> I've merged and published the new release. Thanks for the contribution !
> 
> 
> 
> Not too sure what you mean with compilation and arm. python doesn't really compile and especially not cross compile. it uses on whatever python engine is installed. Here I am merely testing on 2 different python versions for backward compatibiilty.

I'm fairly new to python, so forgive me, still learning the ins and outs.

When I created a new `python-3.12` venv, and ran `pixi run build`, I got a warning about using Rosetta for emulation. But it installed, and ran w/o issue, unit tests and all.

When I updated `pixi.toml` to add `osx-arm64`, `pixi run build` failed to complete successfully.

Probably not worth investigating, when Rosetta emulation works just fine.

Thanks for all your help!
