### ISSUE TITLE
delete_movie does not delete files

### ISSUE THREAD

**Issue by marc0janssen** [vche/pycliarr#5]
Same as delete series... the movie files are not deleted.

**Comment by vche** [comment]
Please provide an example of the call made, and the output and ensure you have set the proper option.

**Comment by marc0janssen** [comment]
if data[1] == "serie":
                    self.sonarr_node.delete_serie(serie_id=int(data[2]))
                else:
                    self.radarr_node.delete_movie(movie_id=int(data[2]))


The movie removed for radarr but the files stay on the disk

**Comment by vche** [comment]
Fixed in 1.0.8
